{
  "formatVersion": "1.1",
  "component": {
    "group": "net.momirealms",
    "module": "craft-engine-bukkit",
    "version": "26.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "craft-engine-bukkit-26.9.jar",
          "url": "craft-engine-bukkit-26.9.jar",
          "size": 2214596,
          "sha512": "7fd187c75ec7c2640e81bb688f85f41fa8494f442603d350a0379dc57b80f94d1a351de9759f1c74eb32247d8b26f6b682c152e007058a00d4503509244d8564",
          "sha256": "f7e02cabc4d8d91b4eb096d304a79e91045f4a76e576140d4d1f7e6da6843a76",
          "sha1": "11f83eb331ebc81cce9645ed6ce2a735c13a6c34",
          "md5": "8d9b63946342c9a6f3e3c54bd256736e"
        }
      ]
    }
  ]
}
