{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.btc.velocity",
    "module": "api",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.5.0-jre"
          }
        },
        {
          "group": "io.hotmoka",
          "module": "toml4j",
          "version": {
            "requires": "0.7.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi"
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.velocitypowered",
          "module": "velocity-brigadier",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-hocon",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-gson",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-3.4.0.jar",
          "url": "api-3.4.0.jar",
          "size": 229759,
          "sha512": "f6851c725395b3b766d9f64ffee7ee4650549320deae5e06db7b3a2336cf69f4eb666213c73a4720fd31d6d8106240e2f9e65ae5a5d744fc873d063beda9ede1",
          "sha256": "0cb0bd44957ad01d66e6d06fb4c3f611ffa3c039d3b4725aee99af549356f44c",
          "sha1": "5a978631f5e206f13f2d9ec450eb80bd2a842ce6",
          "md5": "47360e206b272fbd266218229f89b2b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.5.0-jre"
          }
        },
        {
          "group": "io.hotmoka",
          "module": "toml4j",
          "version": {
            "requires": "0.7.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi"
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.velocitypowered",
          "module": "velocity-brigadier",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-hocon",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-gson",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "api-3.4.0.jar",
          "url": "api-3.4.0.jar",
          "size": 229759,
          "sha512": "f6851c725395b3b766d9f64ffee7ee4650549320deae5e06db7b3a2336cf69f4eb666213c73a4720fd31d6d8106240e2f9e65ae5a5d744fc873d063beda9ede1",
          "sha256": "0cb0bd44957ad01d66e6d06fb4c3f611ffa3c039d3b4725aee99af549356f44c",
          "sha1": "5a978631f5e206f13f2d9ec450eb80bd2a842ce6",
          "md5": "47360e206b272fbd266218229f89b2b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-3.4.0-sources.jar",
          "url": "api-3.4.0-sources.jar",
          "size": 197444,
          "sha512": "c563a090e13d5b33b0c6f66d4a77323e1bbedc71a741774ae6482c972ebc66a098195dcc901e3a2375a720f0d57d910fd178cb4db5a2f8c2a15b7a99cce1053a",
          "sha256": "ca47a064c9dd69ed8ca28a4d11dd7bb77eba864fa2e6fc8441b9206351cf8a1e",
          "sha1": "96c2096c083a9c9f9ce09a9fc23c8d3e3f4196ec",
          "md5": "0500932b4be79bffa9f66800a75b976b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-3.4.0-javadoc.jar",
          "url": "api-3.4.0-javadoc.jar",
          "size": 1420505,
          "sha512": "1dee43b748797b0bb287d3ec06a2a3c579b1fa984274ae223ea29636f8595d132f2bf755c10bebeb2908e85fb829aa6e306ad2df0a65dbef315cb9a45271b570",
          "sha256": "a58138e150f8160fb01475754f196e70505f452c4aa72701b25afa7e0ba17474",
          "sha1": "9cc56bcb71c6cead9b2b77894272c55ff5658501",
          "md5": "49bab9a4baa3cc31763de577c11671ca"
        }
      ]
    }
  ]
}
