{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.miniplaceholders",
    "module": "miniplaceholders-kotlin-ext",
    "version": "3.2.0-26.3-BTC-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "miniplaceholders-kotlin-ext-3.2.0-26.3-BTC-1.jar",
          "url": "miniplaceholders-kotlin-ext-3.2.0-26.3-BTC-1.jar",
          "size": 5905,
          "sha512": "63dffa5376855ff31e50f6cd4c143503ac052e27a83efed248658f9e17894d91fcf06eeba817a749d275e0ab1bc18055e3c12a861d9f1bf60a20beca7fccd684",
          "sha256": "a6a3c7236f06c59c760c74cee250b2a1503d75824cd9102b6d0f4ff23fc18690",
          "sha1": "b75d019c3b862dee0cc7ada1329b0da22fd44b28",
          "md5": "f9f39496b5044c129137cadcba110b46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "miniplaceholders-kotlin-ext-3.2.0-26.3-BTC-1.jar",
          "url": "miniplaceholders-kotlin-ext-3.2.0-26.3-BTC-1.jar",
          "size": 5905,
          "sha512": "63dffa5376855ff31e50f6cd4c143503ac052e27a83efed248658f9e17894d91fcf06eeba817a749d275e0ab1bc18055e3c12a861d9f1bf60a20beca7fccd684",
          "sha256": "a6a3c7236f06c59c760c74cee250b2a1503d75824cd9102b6d0f4ff23fc18690",
          "sha1": "b75d019c3b862dee0cc7ada1329b0da22fd44b28",
          "md5": "f9f39496b5044c129137cadcba110b46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "miniplaceholders-kotlin-ext-3.2.0-26.3-BTC-1-sources.jar",
          "url": "miniplaceholders-kotlin-ext-3.2.0-26.3-BTC-1-sources.jar",
          "size": 2699,
          "sha512": "e0d80e8a0f1dea65441d89fd8ac43c1bb43a10b24bb6d70c250ba75ad0882f390dcb201dc10c93e6d897f7848be26125524bcf537c5ee0e853090ed747fd9541",
          "sha256": "c72bb91e89bc73e43f94a156fe0dea18b91e9e7ac913c6e617335819a747df83",
          "sha1": "7fb8291a0fef6667126e2dc29cd46b5739e54540",
          "md5": "02f572053b68336a6c661651fc116304"
        }
      ]
    }
  ]
}
