{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.btc.velocity",
    "module": "api",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.5.0-jre"
          }
        },
        {
          "group": "io.hotmoka",
          "module": "toml4j",
          "version": {
            "requires": "0.7.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi"
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.velocitypowered",
          "module": "velocity-brigadier",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-hocon",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-gson",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-0.1.jar",
          "url": "api-0.1.jar",
          "size": 232171,
          "sha512": "0be719da961f7d923351f079525829468ece54fe1286c456bde87bac17080419676475457a088456ffbce60cc9d694783dbedd324fa6a47ca53ac4b613192fd4",
          "sha256": "7215f30367afff0b756d79ff82c788a79abad5cb35bbb4c03ff10e57199cfbfd",
          "sha1": "d6d75b5cb327aefd6c8556ff100a90035b54e1c4",
          "md5": "f08a1649e070fd4567fd577c36bfc467"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.5.0-jre"
          }
        },
        {
          "group": "io.hotmoka",
          "module": "toml4j",
          "version": {
            "requires": "0.7.3"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi"
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.velocitypowered",
          "module": "velocity-brigadier",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-hocon",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-gson",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "api-0.1.jar",
          "url": "api-0.1.jar",
          "size": 232171,
          "sha512": "0be719da961f7d923351f079525829468ece54fe1286c456bde87bac17080419676475457a088456ffbce60cc9d694783dbedd324fa6a47ca53ac4b613192fd4",
          "sha256": "7215f30367afff0b756d79ff82c788a79abad5cb35bbb4c03ff10e57199cfbfd",
          "sha1": "d6d75b5cb327aefd6c8556ff100a90035b54e1c4",
          "md5": "f08a1649e070fd4567fd577c36bfc467"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-0.1-sources.jar",
          "url": "api-0.1-sources.jar",
          "size": 197991,
          "sha512": "b8833ea9d8d4b74a7cfda7be0ac2d99881d2ca2b4712c5d6a09350f3ed49328d651313849a1007b428df02912944a39a54d6866c8037909f9f27a121c4925171",
          "sha256": "2f5a34cf0f992114181cd5c5fa730b65007b88bfd08f077ee14e262cd46b39a0",
          "sha1": "042c740a6603f974919559291d5840a3eb000701",
          "md5": "9e566107048f25ce7baa60e6407156a7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-0.1-javadoc.jar",
          "url": "api-0.1-javadoc.jar",
          "size": 1432998,
          "sha512": "57bbda5bf0c1d7d709145eb88a2aa7b3e66ee9de5bf2b7a992a580a89e651abfcfbe46c1c1430b6a2336c17439fe3c7d4d85526c2407e039ddb059a5b4f11e37",
          "sha256": "8e806ed22b6a2af7158a4a95c55ee533df2a3d18a54bd72daca14b3f0ac01ff7",
          "sha1": "4c27e1331fe134ac7eca70d14106dfe68e4259e6",
          "md5": "a8f3a315faf386b7826dd5ee103bc074"
        }
      ]
    }
  ]
}
