{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.toxicity188",
    "module": "bettermodel-fabric",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.semver4j",
          "module": "semver4j",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "dynamicuv",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "java-mesh",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "bettermodel-api",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "bettermodel-mod-api",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "bettermodel-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.incendo",
          "module": "cloud-fabric",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "bettermodel-fabric-3.5.0.jar",
          "url": "bettermodel-fabric-3.5.0.jar",
          "size": 4510943,
          "sha512": "abcfdc7cd1eab16cc8cb2b8cb282064be4f0cb0d0efa88e6ca8dfebe260561c7b174d863373e0dd682702e157927767e83860ba86392c55466dc34809ad38c14",
          "sha256": "60e28a8656430741f76842f615a03a86fa99b5017b791faaf13b5e0ee428ceb1",
          "sha1": "7c33aadb3806891ec0028e0cdda4467b9ea386cb",
          "md5": "13d7fc958b660ac01b2d6225469a5373"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "2.0.6+fcdff87f5d"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "3.1.2+fcdff87f5d"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-data-attachment-api-v1",
          "version": {
            "requires": "2.2.30+3434d6d95d"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-entity-events-v1",
          "version": {
            "requires": "6.0.4+3434d6d95d"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-events-interaction-v0",
          "version": {
            "requires": "5.3.6+3434d6d95d"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "4.1.9+ffef5f675d"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "6.3.8+fcdff87f5d"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-transitive-access-wideners-v1",
          "version": {
            "requires": "8.1.16+52268a0e5d"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "eu.pb4",
          "module": "polymer-resource-pack",
          "version": {
            "requires": "0.18.2+26.3"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "armormodel",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "org.semver4j",
          "module": "semver4j",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "dynamicuv",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "java-mesh",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "bettermodel-api",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "bettermodel-mod-api",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "bettermodel-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-platform-fabric",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.incendo",
          "module": "cloud-fabric",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "bettermodel-fabric-3.5.0.jar",
          "url": "bettermodel-fabric-3.5.0.jar",
          "size": 4510943,
          "sha512": "abcfdc7cd1eab16cc8cb2b8cb282064be4f0cb0d0efa88e6ca8dfebe260561c7b174d863373e0dd682702e157927767e83860ba86392c55466dc34809ad38c14",
          "sha256": "60e28a8656430741f76842f615a03a86fa99b5017b791faaf13b5e0ee428ceb1",
          "sha1": "7c33aadb3806891ec0028e0cdda4467b9ea386cb",
          "md5": "13d7fc958b660ac01b2d6225469a5373"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bettermodel-fabric-3.5.0-sources.jar",
          "url": "bettermodel-fabric-3.5.0-sources.jar",
          "size": 61945,
          "sha512": "4a026b857aa5c0a5daf4306f83e3b170a660f401a1c4b31eb1537a37f27300a4ca6120f50e5400d68a23c8ea6ab571fa036aa96801f38a3eef1fbcb69e56f0bc",
          "sha256": "eaeddfa5b794470a90dfcb166a2f2c3962bc785af2aba4110532967e664cd8de",
          "sha1": "ab8b849e230217a85c62f2838c6bbb88cc39d6d2",
          "md5": "5f236ceaa44a3818abb8029e3f4216ac"
        }
      ]
    }
  ]
}
