{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.toxicity188",
    "module": "bettermodel-core",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.semver4j",
          "module": "semver4j",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "dynamicuv",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "java-mesh",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "bettermodel-api",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "bettermodel-core-3.5.0.jar",
          "url": "bettermodel-core-3.5.0.jar",
          "size": 380208,
          "sha512": "7f246dd1e1798e4eeb214353f38be925bea53e227d1662aed5c32826565749540eb8461ff67d957d43cb28ab3c751b0b39c2cbf02c1f75d9da714bca71c16856",
          "sha256": "fce2953fc611d5957983e1cbf2d880a939356422b0ec75b3914bb98137f9deb3",
          "sha1": "4266a2b58ab80bf98c79e0aa0cc4e5cf471e7760",
          "md5": "bf3dc72d98928b215bf8ef4499d7f8ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.semver4j",
          "module": "semver4j",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "dynamicuv",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "java-mesh",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.2.4"
          }
        },
        {
          "group": "io.github.toxicity188",
          "module": "bettermodel-api",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "bettermodel-core-3.5.0.jar",
          "url": "bettermodel-core-3.5.0.jar",
          "size": 380208,
          "sha512": "7f246dd1e1798e4eeb214353f38be925bea53e227d1662aed5c32826565749540eb8461ff67d957d43cb28ab3c751b0b39c2cbf02c1f75d9da714bca71c16856",
          "sha256": "fce2953fc611d5957983e1cbf2d880a939356422b0ec75b3914bb98137f9deb3",
          "sha1": "4266a2b58ab80bf98c79e0aa0cc4e5cf471e7760",
          "md5": "bf3dc72d98928b215bf8ef4499d7f8ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bettermodel-core-3.5.0-sources.jar",
          "url": "bettermodel-core-3.5.0-sources.jar",
          "size": 188304,
          "sha512": "e7886412ca9a39d8400d55f7d9d7cd4f0472a452bfed19b1178cb5a7fd93f312e15dbb7b497cd3db5e043099991ce72a7f5d3a709bb4ca5f06f783e6a7623665",
          "sha256": "90f1cd4a6168c1f24bae4ca1cf3656e246ed2d0af03d285716b183d7d67677ed",
          "sha1": "e97f9eb27d12e367c96319e8d45677799a56ba37",
          "md5": "04e91823ca443ff12611c7a80686667b"
        }
      ]
    }
  ]
}
