{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.toxicity188",
    "module": "BetterHud-api",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.toxicity188",
          "module": "BetterCommand",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.semver4j",
          "module": "semver4j",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "BetterHud-api-2.1.0.jar",
          "url": "BetterHud-api-2.1.0.jar",
          "size": 80901,
          "sha512": "95eaabba2d7eca18fd53c07c1408d9891703440466302377e2534653f691882e952875f7ead596526496af9d2d4911a7a6bef3a789655268bf6df8a16033f2d7",
          "sha256": "889ccbec4e45f1e951dfc23522afd632c935dbbef4a639073e37e93df04d9444",
          "sha1": "e915ad9857e402cf6e66b151ee2e3ddc4d061c6d",
          "md5": "9f61f3b43c3bfa6a62b60d30a0106364"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.toxicity188",
          "module": "BetterCommand",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.semver4j",
          "module": "semver4j",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "BetterHud-api-2.1.0.jar",
          "url": "BetterHud-api-2.1.0.jar",
          "size": 80901,
          "sha512": "95eaabba2d7eca18fd53c07c1408d9891703440466302377e2534653f691882e952875f7ead596526496af9d2d4911a7a6bef3a789655268bf6df8a16033f2d7",
          "sha256": "889ccbec4e45f1e951dfc23522afd632c935dbbef4a639073e37e93df04d9444",
          "sha1": "e915ad9857e402cf6e66b151ee2e3ddc4d061c6d",
          "md5": "9f61f3b43c3bfa6a62b60d30a0106364"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterHud-api-2.1.0-sources.jar",
          "url": "BetterHud-api-2.1.0-sources.jar",
          "size": 42061,
          "sha512": "72702051370649753045663cb882b3350cbc2e4f9d4b8437019d8fc81024d3018bcfb57fc935d30032995e849a3af9c5039254c43a45ef34c72a0e1ef6a2bb93",
          "sha256": "093de247f195c76510e10cefa94cc1b8b1e15b281ee1731ed0bd06ec53e55aa5",
          "sha1": "ce07e7d3fdf845b3ed53e2f817589d023c705e9f",
          "md5": "4debf06c6b1abf0134136c7e7e0ec10b"
        }
      ]
    }
  ]
}
